package aoc2024

import (
	"strings"
	"testing"

	"github.com/jacoelho/advent-of-code-go/internal/aoc"
)

func Test_day08p01(t *testing.T) {
	tests := []aoc.TestInput{
		{
			Input: strings.NewReader(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............0`),
			Want: "14",
		},
		{
			Input: aoc.FileInput(t, 2024, 8),
			Want:  "409",
		},
	}

	aoc.AOCTest(t, day08p01, tests)
}

func Test_day08p02(t *testing.T) {
	tests := []aoc.TestInput{
		{
			Input: strings.NewReader(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`),
			Want: "34",
		},
		{
			Input: aoc.FileInput(t, 2024, 8),
			Want:  "1308",
		},
	}

	aoc.AOCTest(t, day08p02, tests)
}
